# Generated by Django 3.2.3 on 2021-05-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hilfreichetabellen_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='hilfreichetabellen',
            name='is_file_change',
            field=models.BooleanField(default=False, verbose_name='Is table changed'),
        ),
    ]
