# Generated by Django 3.2.3 on 2021-05-26 17:35

from django.db import migrations, models
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user/avatars', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('nickname', models.CharField(max_length=50, null=True, verbose_name='Ник')),
                ('balance', models.IntegerField(default=1000, verbose_name='Баланс')),
                ('add_balance', models.IntegerField(default=0, verbose_name='Баланс снимаемый')),
                ('total_add', models.IntegerField(default=0, verbose_name='Баланс пополнен всего')),
                ('total_remove', models.IntegerField(default=0, verbose_name='Баланс снят всего')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('sex', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол')),
                ('study', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('work', models.TextField(blank=True, null=True, verbose_name='Работа')),
                ('profession', models.TextField(blank=True, null=True, verbose_name='Профессия')),
                ('games_count', models.IntegerField(default=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
