# Generated by Django 3.2.3 on 2021-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210527_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_12_months_account',
            field=models.BooleanField(default=False, verbose_name='12 months account'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_3_months_account',
            field=models.BooleanField(default=False, verbose_name='3 months account'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_6_months_account',
            field=models.BooleanField(default=False, verbose_name='6 months account'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Is VIP ?'),
        ),
    ]
